[package]
name = "hydroflow_plus_test"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]
hydroflow = { path = "../hydroflow", version = "^0.5.0", features = [ "cli_integration" ] }
hydroflow_plus = { path = "../hydroflow_plus", version = "^0.5.0" }
tokio = { version = "1.16", features = [ "full" ] }
stageleft = { path = "../stageleft", version = "^0.1.0" }
regex = "1"
serde = "1"
hydroflow_plus_test_macro = { path = "../hydroflow_plus_test_macro" }

[build-dependencies]
stageleft_tool = { path = "../stageleft_tool", version = "^0.1.0" }

[dev-dependencies]
insta = "1.7.1"
