[package]
name = "hydroflow_plus_kvs_flow"
publish = false
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
hydroflow_plus = { path = "../hydroflow_plus", version = "^0.5.0" }
stageleft = { path = "../stageleft", version = "^0.5.0" }
regex = "1"
serde = "1"
