[package]
name = "hydroflow_plus_example_runtime"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]
hydroflow_plus = { path = "../hydroflow_plus", version = "^0.4.0" }
hydroflow_plus_example_flow = { path = "../hydroflow_plus_example_flow" }
serde = "1"
